export default {
  "GET /get/list": {
    code: 100000,
    data: 141314,
  },
  //概览
  "POST /algorithm/name/groupByScene": {
    status: "success",
    msg: "request success",
    code: 100000,
    data: {
      anomaly_detection: {
        displayNames: "单指标时序数据异常检测",
        displayDescriptions:
          "单指标时序数据异常检测的描述单指标时序数据异常检测的描述单指标时序数据异常检测的描述",
        algorithmNames: [{}, {}],
        type: "anomaly_detection",
        name: "anomaly_detection",
      },
      forecasting: {
        displayNames: "单指标时序数据预测",
        displayDescriptions:
          "单指标时序数据预测单指标时序数据预测单指标时序数据预测单指标时序数据预测单指标时序数据预测单指标时序数据预测",
        algorithmNames: [{}, {}],
        type: "forecasting",
        name: "forecasting",
      },
      log_parsing: {
        displayNames: "日志模式解析",
        displayDescriptions:
          "日志模式解析日志模式解析日志模式解析日志模式解析日志模式解析日志模式解析日志模式解析日志模式解析",
        algorithmNames: [{}, {}],
        type: "log_parsing",
        name: "log_parsing",
      },
      log_anomaly_detection: {
        displayNames: "日志异常检测",
        displayDescriptions:
          "日志异常检测日志异常检测日志异常检测日志异常检测日志异常检测日志异常检测日志异常检测日志异常检测日志异常检测",
        algorithmNames: [{}, {}],
        type: "log_anomaly_detection",
        name: "log_anomaly_detection",
      },
      root_cause_analysis: {
        displayNames: "根因分析",
        displayDescriptions:
          "根因分析根因分析根因分析根因分析根因分析根因分析根因分析根因分析根因分析根因分析根因分析根因分析",
        algorithmNames: [{}, {}],
        type: "root_cause_analysis",
        name: "root_cause_analysis",
      },
      alerting: {
        displayNames: "告警降噪",
        displayDescriptions:
          "告警降噪告警降噪告警降噪告警降噪告警降噪告警降噪告警降噪告警降噪告警降噪告警降噪告警降噪告警降噪告警降噪告警降噪",
        algorithmNames: [{}, {}],
        type: "alerting",
        name: "alerting",
      },
    },
  },
  //获取数据源管理-列表
  "POST /datasource/list": {
    status: "success",
    msg: "request success",
    code: 100000,
    data: {
      pageNum: 1,
      pageSize: 10,
      totalSize: 15,
      totalPages: 2,
      content: [
        {
          id: "223369477557936128",
          accountId: "110",
          updatedTime: 1637737060000,
          createdTime: 1637737060000,
          name: "XX站1111",
          type: "FILE",
          dataType: "TIME_SERIES",
          description: "",
          isDeleted: 0,
          dataTags: [],
          fieldConfig: {
            type: "TIME_SERIES",
            model: "model",
            metric: "metric_key",
            target: "target",
            tags: "metric_tags",
            time: "timestamp",
            value: "value",
          },
          fieldConfigDisplay: {
            type: "TIME_SERIES",
            model: "model",
            metric: "metric_key",
            target: "target",
            tags: "metric_tags",
            time: "timestamp",
            value: "value",
          },
          sourceConfig: {
            type: "FILE",
            tableName: "doia_csv_data_source_table",
            databaseName: "doia_result",
            dataSourceId: "223369477557936128",
            fileName: "XX站_XX设备_柜上地电波.csv",
            uploadCount: 4591,
            invalidCount: 0,
            totalCount: 4591,
            ckCount: 0,
            processing: false,
          },
          state: 0,
        },
        {
          id: "223369303930527744",
          accountId: "110",
          updatedTime: 1637737040000,
          createdTime: 1637737040000,
          name: "XX设备222222",
          type: "FILE",
          dataType: "TIME_SERIES",
          description: "",
          isDeleted: 0,
          dataTags: [],
          fieldConfig: {
            type: "TIME_SERIES",
            model: "model",
            metric: "metric_key",
            target: "target",
            tags: "metric_tags",
            time: "timestamp",
            value: "value",
          },
          fieldConfigDisplay: {
            type: "TIME_SERIES",
            model: "model",
            metric: "metric_key",
            target: "target",
            tags: "metric_tags",
            time: "timestamp",
            value: "value",
          },
          sourceConfig: {
            type: "FILE",
            tableName: "doia_csv_data_source_table",
            databaseName: "doia_result",
            dataSourceId: "223369303930527744",
            fileName: "XX站_XX设备_一侧电流A相.csv",
            uploadCount: 26508,
            invalidCount: 0,
            totalCount: 26508,
            ckCount: 0,
            processing: false,
          },
          state: 0,
        },
        {
          id: "223369127014785024",
          accountId: "110",
          updatedTime: 1637737019000,
          createdTime: 1637737019000,
          name: "XX站_XX设备_低压管母接头温度二段(A)",
          type: "FILE",
          dataType: "TIME_SERIES",
          description: "",
          isDeleted: 0,
          dataTags: [],
          fieldConfig: {
            type: "TIME_SERIES",
            model: "model",
            metric: "metric_key",
            target: "target",
            tags: "metric_tags",
            time: "timestamp",
            value: "value",
          },
          fieldConfigDisplay: {
            type: "TIME_SERIES",
            model: "model",
            metric: "metric_key",
            target: "target",
            tags: "metric_tags",
            time: "timestamp",
            value: "value",
          },
          sourceConfig: {
            type: "FILE",
            tableName: "doia_csv_data_source_table",
            databaseName: "doia_result",
            dataSourceId: "223369127014785024",
            fileName: "XX站_XX设备_低压管母接头温度二段(A).csv",
            uploadCount: 39918,
            invalidCount: 0,
            totalCount: 39918,
            ckCount: 0,
            processing: false,
          },
          state: 0,
        },
        {
          id: "223368945921515520",
          accountId: "110",
          updatedTime: 1637736997000,
          createdTime: 1637736997000,
          name: "交易量_周期数据",
          type: "FILE",
          dataType: "TIME_SERIES",
          description: "",
          isDeleted: 0,
          dataTags: [],
          fieldConfig: {
            type: "TIME_SERIES",
            model: "model",
            metric: "metric_key",
            target: "target",
            tags: "metric_tags",
            time: "timestamp",
            value: "value",
          },
          fieldConfigDisplay: {
            type: "TIME_SERIES",
            model: "model",
            metric: "metric_key",
            target: "target",
            tags: "metric_tags",
            time: "timestamp",
            value: "value",
          },
          sourceConfig: {
            type: "FILE",
            tableName: "doia_csv_data_source_table",
            databaseName: "doia_result",
            dataSourceId: "223368945921515520",
            fileName: "交易量_周期数据.csv",
            uploadCount: 23040,
            invalidCount: 0,
            totalCount: 23040,
            ckCount: 0,
            processing: false,
          },
          state: 0,
        },
        {
          id: "223368774827466752",
          accountId: "110",
          updatedTime: 1637736976000,
          createdTime: 1637736976000,
          name: "内存可用率_周期趋势数据_1",
          type: "FILE",
          dataType: "TIME_SERIES",
          description: "",
          isDeleted: 0,
          dataTags: [],
          fieldConfig: {
            type: "TIME_SERIES",
            model: "model",
            metric: "metric_key",
            target: "target",
            tags: "metric_tags",
            time: "timestamp",
            value: "value",
          },
          fieldConfigDisplay: {
            type: "TIME_SERIES",
            model: "model",
            metric: "metric_key",
            target: "target",
            tags: "metric_tags",
            time: "timestamp",
            value: "value",
          },
          sourceConfig: {
            type: "FILE",
            tableName: "doia_csv_data_source_table",
            databaseName: "doia_result",
            dataSourceId: "223368774827466752",
            fileName: "内存可用率_周期趋势数据_1.csv",
            uploadCount: 4050,
            invalidCount: 0,
            totalCount: 4050,
            ckCount: 0,
            processing: false,
          },
          state: 0,
        },
      ],
    },
  },
  //获取数据源管理-编辑2-1 查询标签
  "POST /datatag/list": {
    status: "success",
    msg: "request success",
    code: 100000,
    data: {
      totalSize: 0,
      content: [],
    },
  },
  //获取数据源管理-编辑2-2
  "GET /datasource/223417039161745408": {
    status: "success",
    msg: "request success",
    code: 100000,
    data: {
      id: "223417039161745408",
      accountId: "110",
      createdUserId: "2",
      updatedUserId: "2",
      updatedTime: 1637742844000,
      createdTime: 1637742730000,
      name: "指标数据源",
      type: "DODB",
      dataType: "TIME_SERIES",
      isDeleted: 0,
      dataTags: [],
      fieldConfig: {
        type: "TIME_SERIES",
        model: "target_model",
        metric: "metric_key",
        target: "target_name",
        tags: "metric_tags",
        time: "metric_time",
        value: "metric_value",
      },
      sourceConfig: {
        type: "DODB",
        tableName: "leslie01",
        databaseName: "leslie",
        dataStoreId: 20,
        dataStoreName: "原始数据源Leslie",
      },
      state: 0,
    },
  },
  //获取维度key
  "POST task/tagsKey-list": {
    status: "success",
    msg: "request success",
    code: 100000,
    data: {
      dataSourceId: "237388749683254400",
      result: {
        pageNum: 1,
        pageSize: 100,
        totalSize: 1,
        totalPages: 1,
        content: ["tags"],
      },
      existenceMapping: true,
    },
  },
  //获取维度value
  "POST task/tagsValue-list": {
    status: "success",
    msg: "request success",
    code: 100000,
    data: {
      dataSourceId: "237388749683254400",
      result: {
        pageNum: 1,
        pageSize: 100,
        totalSize: 1,
        totalPages: 1,
        content: ["tags_读取时间"],
      },
      existenceMapping: true,
    },
  },
};
